import { Poppins } from "next/font/google";
import Sidebar from "./components/Sidebar";
import Providers from "@/app/providers";
import { auth, signOut } from "@/auth";
import "@/app/globals.css";
import { redirect } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const session = await auth();

  if (session.status === "unauthenticated") redirect("/auth/signin");
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-white w-full`}>
        <div className="flex min-h-screen font-sans text-zinc-950">
          <Providers session={session}>
            <Sidebar user={session?.user} />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
