import { Roboto, Montserrat, Poppins } from "next/font/google";
import "@/app/globals.css";
import { Header } from "../components/Header";
import Providers from "../providers";
import { auth } from "@/auth";

const poppins = Poppins({
  weight: ["300", "400", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers session={session}>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
