import { Poppins } from "next/font/google";
import Providers from "@/app/providers";
import { auth, signOut } from "@/auth";
import "@/app/globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CasesLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="flex min-h-screen bg-zinc-50 font-sans text-zinc-950 ">
          <Providers session={session}>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
